OBJS_$(CONFIG_USE_CORE) += ili9163.o clock_rtc.o serv_core.o clock_serv.o
DEFS_$(CONFIG_ENABLE_DEBUG) += -DCONFIG_ENABLE_DEBUG
OBJS_$(CONFIG_USE_FONT) += font_data.o 
OBJS_$(CONFIG_PERIODIC_TASK) += periodic_task.o
OBJS_$(CONFIG_BUTTON) += button.o

OBJS_$(CONFIG_CLOCK) += clock_main.o
OBJS_$(CONFIG_GYRO) += adxl345.o activity_serv.o activity_main.o

VPATH += $(BASE_DIR)/core
