OBJS_$(CONFIG_USE_CORE) += ili9163.o clock_rtc.o serv_core.o clock_serv.o
DEFS_$(CONFIG_ENABLE_DEBUG) += -DCONFIG_ENABLE_DEBUG
OBJS_$(CONFIG_USE_FONT) += font_data.o 
OBJS_$(CONFIG_PERIODIC_TASK) += periodic_task.o
OBJS_$(CONFIG_EVENT) += event.o

VPATH += $(BASE_DIR)/core
