# libopencm3 config
LIBDEPS += -lopencm3_stm32f1
LIB_OPENCM3_DIR = $(BASE_DIR)/lib/libopencm3
INCLUDE_PATH += -I$(BASE_DIR)/lib/libopencm3/include
LDFLAGS += -L$(LIB_OPENCM3_DIR)/lib
CFLAGS += -DSTM32F1
